title: Meshtastic
description: An opensource hiking, pilot, skiing, secure GPS mesh communicator

url: "https://meshtastic-documentation.jfirwin.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jfirwin

logo: /assets/meshtastic-logo.png
color_scheme: meshtastic

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
